version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Build debug apk and release apk
          command: |
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  device_farm:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: AWS DeviceFarm
          command: ./gradlew :app:devicefarmUpload
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - device_farm:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
